# docker-compose.yml
version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/costbyte
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USERNAME=your_email@gmail.com
      - SMTP_PASSWORD=your_app_password
      - OPENAI_API_KEY=your_openai_api_key
    depends_on:
      - db
      - redis
    volumes:
      - ./logs:/app/logs
      - ./app/ml/models:/app/app/ml/models

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=costbyte
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A app.workers.celery_worker worker --loglevel=info
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/costbyte
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - db
      - redis

  flower:
    image: mher/flower:1.2.0
    command: celery flower --broker=redis://redis:6379/0
    ports:
      - "5555:5555"
    depends_on:
      - redis

volumes:
  postgres_data:
